version: "3.1"
services:
  app:
    container_name: rect-postgres
    image: recruitment-mgmt-service
    build: ./
    ports:
      - "8082:8080"
    depends_on:
      - postgresqldb
  app_2:
    container_name: emp-postgres
    image: emp-mgmt-service
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employees
